### PR TITLE
Implemented scrypt.

### PR DESCRIPTION
**Pull request by Bren2010**
Pretty simple, straight from the [RFC](http://tools.ietf.org/html/draft-josefsson-scrypt-kdf-01) implementation.

It seems slow, and that's why the fourth test vector is disabled.  I'm not aware of anything, but if I missed some big performance optimization, lmk.

### CODE REVIEW

**Comment by Nilos** [comment]
I guess if you move your functions into a less local namespace they will be optimized better. But that was only my first idea after looking at it for 5 seconds. Will take a closer look soon.

**Comment by Nilos** [comment]
@ggozad As far as I remember you implemented scrypt too, any chance you might have a look at this implementation?

**Comment by Nilos** [comment]
(Sorry for closing - wrong button)

**Comment by ggozad** [comment]
Absolutely, afk atm but will do so asap

**Comment by ggozad** [comment]
This is well written. A few comments
* imo you should sanity check the parameters, i.e

        var SIZE_MAX = Math.pow(2, 32) - 1;
        if (r * p >= Math.pow(2, 30))
            throw "The parameters r, p must satisfy r * p < 2^30";
        if ((N < 2) || (N & (N - 1) !== 0))
            throw "The parameter N must be a power of 2.";
        if (N > SIZE_MAX / 128 / r)
            throw "N too big.";
        if (r > SIZE_MAX / 128 / p)
            throw "r too big.";

* You might improve speed by flipping endian directly, something like:

        function flipEndian(x) {
            var first = x & 0xFF,
            second = (x >>> 8) & 0xFF,
            third = (x >>> 16) & 0xFF,
            fourth = (x >>> 24) & 0xFF;
            return (first << 24) | (second << 16) | (third << 8) | fourth;
        }

This needs some benchmarking, I am not sure when I can get the time to do it, please beat me to it ;)

* Here are additional test vectors including unicode.

            {
                "salt": "salt",
                "password": "password",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "6d1bb878eee9ce4a7b77d7a44103574d4cbfe3c15ae3940f0ffe75cd5e1e0afa"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "6d1bb878eee9ce4a7b77d7a44103574d4cbfe3c15ae3940f0ffe75cd5e1e0afa"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 2,
                "r": 1,
                "p": 2,
                "dkLen": 32,
                "expected": "4db52954f6ece830ebef61b6613b9f1dfd921922d32a1af5b719d15a6676e8ad"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 2,
                "r": 2,
                "p": 1,
                "dkLen": 32,
                "expected": "b6902e4c128feb4b3a475d59773bc4b25e44080cea51d7526b18986c52008386"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 4,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "2ef4390d867dcad84fbb1c064e7fe984e1e9850922ac45c11b2f30c85043f9bd"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 48,
                "expected": "6d1bb878eee9ce4a7b77d7a44103574d4cbfe3c15ae3940f0ffe75cd5e1e0afadb0a556b482b5dcb0d1a54b6e4070beb"
            },
            {
                "salt": "salt",
                "password": "password",
                "N": 4,
                "r": 2,
                "p": 2,
                "dkLen": 48,
                "expected": "89d93e71c0cae21fb524624e6e0229ecae4fb727fb8e5b5f705aaed078aa455fba9e2186b6d5c7dcd7c9561affefd597"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "2e40cbd0f2e5b348d11b25ce977f572c20bbb133b188c5b182f939e92f5581c1"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 2,
                "r": 1,
                "p": 2,
                "dkLen": 32,
                "expected": "b8f439cd39d8c2db78fbc6846bbe4c7af559039af2a44140f4648333bd706a9f"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 2,
                "r": 2,
                "p": 1,
                "dkLen": 32,
                "expected": "60ecb015fc3e8ee29c05253d3827639cee3163ba9e724e84675be7923101aba6"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 4,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "0ca4071216a28c62c86e9b6499de4df73db413cb8f6af8e7210dbedb908340d3"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 48,
                "expected": "2e40cbd0f2e5b348d11b25ce977f572c20bbb133b188c5b182f939e92f5581c16f89084a1ceea4d5b52050498bd94ba5"
            },
            {
                "salt": "saltSALTsaltSALTsaltSALTsaltSALTsalt",
                "password": "passwordPASSWORDpassword",
                "N": 4,
                "r": 2,
                "p": 2,
                "dkLen": 48,
                "expected": "e5f5bce126455eec251b65667e0feb532b07ffcf56164c1b7e81e6cdd88a647cf679d16a7fe8d640de40028df832fd19"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "26e5228d9800146660ad3a9b3e264e7aff9eb0fc68bcc36ee581ec037c4d5a06"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 2,
                "r": 1,
                "p": 2,
                "dkLen": 32,
                "expected": "21131d0da3e4c7250bc108e61ed6afcb6c2b2550b550846b190141ffee12f184"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 2,
                "r": 2,
                "p": 1,
                "dkLen": 32,
                "expected": "72912cd0b78ff614ce9e45773ef2b03e47185ad94f97cbd03337c68f62bc8fca"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 4,
                "r": 1,
                "p": 1,
                "dkLen": 32,
                "expected": "9ab1c590b7651ec11bfd3e6659ad950c39d93f3bba5f73585958164e16d15606"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 2,
                "r": 1,
                "p": 1,
                "dkLen": 48,
                "expected": "26e5228d9800146660ad3a9b3e264e7aff9eb0fc68bcc36ee581ec037c4d5a06794abf829f0042f0884a7b9de15471d5"
            },
            {
                "salt": "sa\u0000lt",
                "password": "pass\u0000word",
                "N": 4,
                "r": 2,
                "p": 2,
                "dkLen": 48,
                "expected": "2c0ea11828a8a4f4991349c2c6c5ff2266aa543c27d876b5ae7a813dd0bb4c0da0d6aadd3d031063502f05faa527ac66"
            },
            {
                "salt": "",
                "password": "",
                "N": 16,
                "r": 1,
                "p": 1,
                "dkLen": 64,
                "expected": "77d6576238657b203b19ca42c18a0497f16b4844e3074ae8dfdffa3fede21442fcd0069ded0948f8326a753a0fc81f17e8d3e0fb2e0d3628cf35e20c38d18906"
            },
            {
                "salt": "NaCl", // heh
                "password": "password",
                "N": 1024,
                "r": 8,
                "p": 16,
                "dkLen": 64,
                "expected": "fdbabe1c9d3472007856e7190d01e9fe7c6ad7cbc8237830e77376634b3731622eaf30d92e22a3886ff109279d9830dac727afb94a83ee6d8360cbdfa2cc0640"
            },
            {
                "salt": "SodiumChloride",
                "password": "pleaseletmein",
                "N": 16384,
                "r": 8,
                "p": 1,
                "dkLen": 64,
                "expected": "7023bdcb3afd7348461c06cd81fd38ebfda8fbba904f8e3ea9b543f6545da1f2d5432955613f0fcf62d49705242a9af9e61e85dc0d651e40dfcf017b45575887"
            }

**Comment by Bren2010** [comment]
@ggozad Thank you for your advice.  :D  The last commit implements all three of your code changes.
However, I don't actually know how to do benchmarks in SJCL... I don't think there are any (in the codebase, at least).

**Comment by Nilos** [comment]
I think you should still extract the functions out of the main scrypt function. This should make things faster as js engines would have earlier knowledge about those functions (and thus could optimize/compile them earlier).
Also it makes for cleaner less coupled code.

**Comment by Bren2010** [comment]
@Nilos Sorry--I forgot that comment.  There we are.  :)

**Comment by ggozad** [comment]
@Bren2010 I am happy with the implementation. So that we don't have to do it afterwards, in separate pull requests, could you benchmark with a simpler one (which on occasion produces faster compilation)?
You can use something like jsperf.com for the comparison.
Here's the implementation I was using and intended to make a PR after some refactoring.

```
sjcl.misc.scrypt = function(passwd, salt, N, r, p, dkLen) {

    function flipEndian(x) {
        var first = x & 0xFF,
            second = (x >>> 8) & 0xFF,
            third = (x >>> 16) & 0xFF,
            fourth = (x >>> 24) & 0xFF;
        return (first << 24) | (second << 16) | (third << 8) | fourth;
    }

    function sanityCheck() {
        var SIZE_MAX = Math.pow(2, 32) - 1;

        if (r * p >= Math.pow(2, 30))
            throw "The parameters r, p must satisfy r * p < 2^30";
        if ((N < 2) || (N & (N - 1) !== 0))
            throw "The parameter N must be a power of 2.";
        if (N > SIZE_MAX / 128 / r)
            throw "N too big.";
        if (r > SIZE_MAX / 128 / p)
            throw "r too big.";
    }

    function scrypt(passwd, salt, N, r, p, dkLen) {
        var B = sjcl.misc.pbkdf2(passwd, salt, 1, p * 128 * r * 8),
            V = [],
            XY = [];

        for (var i = 0; i < p; i++)
            smix(B, i * 128 * r, r, N, V, XY);

        return sjcl.misc.pbkdf2(passwd, B, 1, dkLen * 8);
    }

    function salsa20_8(B) {
        var x = [], B32 = [], i;

        function R(a, b) {
            return (a << b) | (a >>> (32 - b));
        }

        for (i = 0; i < 16; i++)
            B32[i] = flipEndian(B[i]);

        for (i = 0; i < 16; i++)
            x[i] = B32[i] | 0;

        for (i = 8; i > 0; i -= 2) {
            x[4] ^= R(x[0] + x[12], 7);
            x[8] ^= R(x[4] + x[0], 9);
            x[12] ^= R(x[8] + x[4], 13);
            x[0] ^= R(x[12] + x[8], 18);
            x[9] ^= R(x[5] + x[1], 7);
            x[13] ^= R(x[9] + x[5], 9);
            x[1] ^= R(x[13] + x[9], 13);
            x[5] ^= R(x[1] + x[13], 18);
            x[14] ^= R(x[10] + x[6], 7);
            x[2] ^= R(x[14] + x[10], 9);
            x[6] ^= R(x[2] + x[14], 13);
            x[10] ^= R(x[6] + x[2], 18);
            x[3] ^= R(x[15] + x[11], 7);
            x[7] ^= R(x[3] + x[15], 9);
            x[11] ^= R(x[7] + x[3], 13);
            x[15] ^= R(x[11] + x[7], 18);
            x[1] ^= R(x[0] + x[3], 7);
            x[2] ^= R(x[1] + x[0], 9);
            x[3] ^= R(x[2] + x[1], 13);
            x[0] ^= R(x[3] + x[2], 18);
            x[6] ^= R(x[5] + x[4], 7);
            x[7] ^= R(x[6] + x[5], 9);
            x[4] ^= R(x[7] + x[6], 13);
            x[5] ^= R(x[4] + x[7], 18);
            x[11] ^= R(x[10] + x[9], 7);
            x[8] ^= R(x[11] + x[10], 9);
            x[9] ^= R(x[8] + x[11], 13);
            x[10] ^= R(x[9] + x[8], 18);
            x[12] ^= R(x[15] + x[14], 7);
            x[13] ^= R(x[12] + x[15], 9);
            x[14] ^= R(x[13] + x[12], 13);
            x[15] ^= R(x[14] + x[13], 18);
        }

        for (i = 0; i<16; i++)
            B32[i] = (B32[i] + x[i]) | 0;

        for (i = 0; i < 16; i++)
            B[i] = flipEndian(B32[i]);

        return B;
    }

    function blockxor(S, Si, D, Di, len) {
        len /= 4;
        Si /= 4;
        Di /= 4;
        for (var i = 0; i < len; i++)
            D[Di + i] ^= S[Si + i] | 0;
    }

    function blockcopy(S, Si, D, Di, len) {
        var i;

        len /= 4;
        Si /= 4;
        Di /= 4;

        for (i = 0; i < len; i++)
            D[Di + i] = S[Si + i] | 0;
    }

    function blockmix_salsa8(BY, Bi, Yi, r) {
        var X = [], i;

        blockcopy(BY, Bi + (2 * r - 1) * 64, X, 0, 64);

        for (i = 0; i < 2 * r; i++) {
            blockxor(BY, i * 64, X, 0, 64);
            salsa20_8(X);
            blockcopy(X, 0, BY, Yi + (i * 64), 64);
        }

        for (i = 0; i < r; i++)
            blockcopy(BY, Yi + (i * 2) * 64, BY, Bi + (i * 64), 64);

        for (i = 0; i < r; i++)
            blockcopy(BY, Yi + (i * 2 + 1) * 64, BY, Bi + (i + r) * 64, 64);
    }

    function smix(B, Bi, r, N, V, XY) {
        var Xi = 0,
            Yi = 128 * r,
            i, j;

        blockcopy(B, Bi, XY, Xi, Yi);

        for (i = 0; i < N; i++) {
            blockcopy(XY, Xi, V, i * Yi, Yi);
            blockmix_salsa8(XY, Xi, Yi, r);
        }

        for (i = 0; i < N; i++) {
            j = integerify(XY, Xi, r) & (N - 1);
            blockxor(V, j * Yi, XY, Xi, Yi);
            blockmix_salsa8(XY, Xi, Yi, r);
        }

        blockcopy(XY, Xi, B, Bi, Yi);
    }

    function integerify(B, Bi, r) {
        Bi = Bi + (2 * r - 1) * 64;
        return flipEndian(B[Bi / 4]);
    }

    sanityCheck();
    return scrypt(passwd, salt, N, r, p, dkLen);
};
```

**Comment by Nilos** [comment]
Way better. It would still be awesome if you could namespace it:
```var scryptROMix =```
becomes
```sjcl.misc.scrypt.scryptROMix =```

**Comment by Bren2010** [comment]
Benchmarks:  http://jsperf.com/scrypt-test

On Firefox+Mac, it looks like mine is a pinch faster.

**Comment by ggozad** [comment]
I am +1 for merge.

**Comment by Nilos** [comment]
There seems to be one slowdown with chrome, will investigate (Brens version is 2 times slower in chrome than simplescrypt)

**Comment by ggozad** [comment]
Safari too is 2x slower. Will try to have a look tomorrow too.

**Comment by ggozad** [comment]
Otherwise, let me know if I should make a PR with the simpler version, or I can amend it here.

**Comment by Nilos** [comment]
I would prefer to find out what is causing the slowdown and making it fast in both browsers...

**Comment by ggozad** [comment]
@Bren2010 are you up for some refactoring? I am guessing it's about inlining in your code some of the heavy lifters... There's a direct analogy between mine and yours so it shouldn't be hard. Would be nice to merge this asap.

**Comment by Bren2010** [comment]
I was thinking that the virtue in @ggozad's code was that it seemed really reluctant to allocate new memory, and the last commit is a rewrite to also do that as much as possible.

jsPerf is having independent issues, so I don't have a new comparison to his code, but running the scrypt tests in node went from 5599 ms to 3420 ms.

**Comment by ggozad** [comment]
Yes, allocation is going to be a big factor as it is after all the whole rationale behind scrypt.
It's a pity that jsperf is not gonna be with us for a while. Would it be possible to provide measurements for comparison between my simple one and yours? I am happy with the code otherwise.

**Comment by Bren2010** [comment]
[jsPerf](http://jsperf.com/scrypt-test) is back! :smile:  @Nilos I think the benchmarks are better but there's still variation browser-to-browser.  I don't imagine there's much I can do about that.

**Comment by ggozad** [comment]
+1 for merge.

**Pull request merged**
