### PR TITLE
GCM progressive mode added

### PR DESCRIPTION
**Pull request by ph4r05**
I needed incremental/streaming/progressive GCM mode so I implemented it, now I would like to contribute to SJCL with this code.

I've implemented it so it has the same interface as OCB2 Progressive mode + I've added some convenience functions.

I've also implemented test cases for this GCM implementation.

All comments are welcome!

### CODE REVIEW

**Comment by stbuehler** [comment]
AEAD algorithms should not expose incremental "streaming" APIs, at least not for decryption: you must not use the decrypted data before it has been verified, which can only happen if you have the complete message anyway.

**Comment by Nilos** [comment]
I have to agree with @stbuehler here. This PR might still be useful though if you do not expose the streaming API for decryption. Even though I see advantages in streaming even if one can only verify data integrity after the final bit (e.g. if you have got a large downloadstream, you do not have to wait for all data), the risk of abuse by users unaware of this problem is too high from my point of view.
Another alternative would be to add a warning alike the one used for CBC: https://github.com/bitwiseshiftleft/sjcl/blob/master/core/cbc.js#L11

**Comment by ph4r05** [comment]
@stbuehler is right about the problem user may use it in incorrect way.
But I agree with @Nilos that there are use-cases where this can be helpful - if data to decrypt just cannot be stored in the RAM - in that case I might decrypt it to the temporary file and then use it if GCM HASH/MAC is correct or drop it. 

Moreover there are is already OCB2 mode implemented in SJCL in the streaming mode (AEAD) https://github.com/bitwiseshiftleft/sjcl/blob/master/core/ocb2progressive.js

So If I add appropriate warning as CBC has, would you consider merging this PR?

**Comment by Nilos** [comment]
Yes I would. Even though I do not know when I will find the time to review it.

**Pull request closed without merging**
