### PR TITLE
Create .doclets.yml

### PR DESCRIPTION
**Pull request by lipp**
Adds documentation to doclets.io service. Future tags and master branch will be published **automatically**.

[Preview generated with my account](https://doclets.io/lipp/sjcl/add-to-doclets#dl-sjcl-arrayBuffer-ccm-encrypt)

Doclets also supports "live/editable" examples for the browser, like [this](https://doclets.io/lipp/acme-jsdoc-example/master#dl-greet)! Just replace the @example tag with @playground tag.

@bitwiseshiftleft   If you like this, you are very welcomed to login to https://doclets.io with GitHub OAuth. If you don't like it, I'd be happy to hear what you don't like about it :)

Steps required (3min):
1) @bitwiseshiftleft   logs in to doclets.io
2) @bitwiseshiftleft   adds sjcl
3) @bitwiseshiftleft   merges this PR

### CODE REVIEW

**Comment by Nilos** [comment]
@bitwiseshiftleft is rather inactive and I do not have enough rights to do the requested action. Will keep this PR open for some time though, maybe we get lucky :)

**Comment by lipp** [comment]
@Nilos Thanks! 💯

**Comment by Nilos** [comment]
@bitwiseshiftleft Can you please give me full rights to the repository?

**Comment by Nilos** [comment]
As @bitwiseshiftleft has not responded in almost 2 years I will close this for now.

**Pull request closed without merging**
