### PR TITLE
Serialization/deserialization of public keys added; serialization tests added

### PR DESCRIPTION
**Pull request by miha-stopar**
Serialization/deserialization code was taken from #99, however ecc.js was significantly changed in the meantime and the serialization code needed to be moved to basicKey class, this is why I opened a new PR. Tests have been added.

Note that extendedArguments could be avoided if we change the return statement of basicKey.generateKeys from
```Javascript
return { pub: new sjcl.ecc[cn].publicKey(curve, pub),
             sec: new sjcl.ecc[cn].secretKey(curve, sec) };
```
to
```Javascript
return { pub: new sjcl.ecc[cn].publicKey(curve, pub, cn),
             sec: new sjcl.ecc[cn].secretKey(curve, sec), cn };
```

but it doesn't feel right pushing cn argument twice into it.

### CODE REVIEW

**Comment by Nilos** [comment]
Looks good so far but we can improve on the issue you already identified.

**Comment by Nilos** [comment]
Just define a getType function on the elGamal/ecdsa keys and use that in the serialization

**Comment by Nilos** [comment]
Like this:
```
sjcl.ecc.ecdsa.publicKey.prototype.getType = function () {
  return "ecdsa";
};
```
And then in serialize:
```
this.serialize = function () {
  var exponent = this.get();
  var curveName = sjcl.ecc.curveName(curve);
  return {
    type: this.getType(),
    secretKey: true,
    exponent: sjcl.codec.hex.fromBits(exponent),
    curve: curveName
  };
};
```

**Comment by miha-stopar** [comment]
Yes, better. I applied this approach.

**Comment by borisirota** [comment]
@miha-stopar Hi, thanks for this PR!
Any reason to serialize with hex instead of base64 which gives shorter result ?

**Comment by miha-stopar** [comment]
@borisirota This PR was based on #99 where hex was used. @Nilos any reason for this?

**Comment by Nilos** [comment]
No and I think base64 would be better!

**Comment by miha-stopar** [comment]
I had a look at it and the problem is that sjcl.bn constructor can take a hex, but not a base64 string. This is needed in deserialize function: 
var exponent = new sjcl.bn(key.exponent)
As the length of keys is probably not such an issue, I would leave as it is.

**Comment by borisirota** [comment]
I see. Well it can be like the public key case which being converted from hex to bits and then to curve. So here it can be converted to bits and then to hex. It doesn't really affects the runtime (and happens only once in most cases) while it can save 1/3 of the space and it does can have some affect when working with a lot of keys especially long ones.

@miha-stopar @Nilos What do you think ? does the conversion from base64 to hex is something to consider ?

**Comment by Nilos** [comment]
I don't think the library should do it. If you need shorter sizes, simply translate the data yourself.

**Comment by borisirota** [comment]
ok thanks!

**Pull request merged**
